CREATE TABLE IF NOT EXISTS usuarios (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    login VARCHAR(100) NOT NULL,
    hash TEXT NOT NULL,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    perfil VARCHAR(100) DEFAULT 'USUARIO',
    data_modificacao TIMESTAMP,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
    );