spring.application.name=o-pai-o

spring.datasource.url=jdbc:postgresql://localhost:5432/DevLapa
spring.datasource.username=postgres
spring.datasource.password=1973

spring.datasource.driver-class-name=org.postgresql.Driver